version: '3.8'

services:
  web-server:
    depends_on:
      - db
    build: server/
    restart: always
    volumes:
      - ./server:/var/www/html
    links:
      - db
    
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./db/init.sql:/var/www/sql/init.sql
    command: --init-file /var/www/sql/init.sql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: appDB
        MYSQL_USER: user
        MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password

  nginx:
    image: nginx:latest
    restart: always
    privileged: true
    user: root
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - 8003:80
    container_name: nginx

volumes:
  my-db: